# Site settings
title: lucasfcosta
full_name: Lucas Fernandes da Costa
email: fernandesdacostalucas@gmail.com
description: > # 
  Coding, culture and life in general.
  Yes, it's that wide.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.io/lucasfcosta" # the base hostname & protocol for your site
github_username:  lucasfcosta
linkedin_username: lucasfdacosta
twitter_username: lfernandescosta

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo